<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html><head><meta http-equiv="Content-Type" content="text/html;charset=iso-8859-1">
<title>cupp: cupp::exception::cuda_runtime_error Class Reference</title>
<link href="doxygen.css" rel="stylesheet" type="text/css">
<link href="tabs.css" rel="stylesheet" type="text/css">
</head><body>
<!-- Generated by Doxygen 1.5.1 -->
<div class="tabs">
  <ul>
    <li><a href="index.html"><span>Main&nbsp;Page</span></a></li>
    <li id="current"><a href="annotated.html"><span>Classes</span></a></li>
    <li><a href="files.html"><span>Files</span></a></li>
    <li><a href="pages.html"><span>Related&nbsp;Pages</span></a></li>
  </ul></div>
<div class="tabs">
  <ul>
    <li><a href="annotated.html"><span>Class&nbsp;List</span></a></li>
    <li><a href="hierarchy.html"><span>Class&nbsp;Hierarchy</span></a></li>
    <li><a href="functions.html"><span>Class&nbsp;Members</span></a></li>
  </ul></div>
<div class="nav">
<b>cupp</b>::<b>exception</b>::<a class="el" href="classcupp_1_1exception_1_1cuda__runtime__error.html">cuda_runtime_error</a></div>
<h1>cupp::exception::cuda_runtime_error Class Reference</h1><!-- doxytag: class="cupp::exception::cuda_runtime_error" --><!-- doxytag: inherits="cupp::exception::exception" -->This exception is thrown when an low-level CUDA error occurs, eg. an internal call to cudaMalloc fails.  
<a href="#_details">More...</a>
<p>
<code>#include &lt;<a class="el" href="cuda__runtime__error_8h-source.html">cuda_runtime_error.h</a>&gt;</code>
<p>
<p>Inheritance diagram for cupp::exception::cuda_runtime_error:
<p><center><img src="classcupp_1_1exception_1_1cuda__runtime__error.png" usemap="#cupp::exception::cuda_runtime_error_map" border="0" alt=""></center>
<map name="cupp::exception::cuda_runtime_error_map">
<area href="classcupp_1_1exception_1_1exception.html" alt="cupp::exception::exception" shape="rect" coords="0,0,218,24">
</map>
<a href="classcupp_1_1exception_1_1cuda__runtime__error-members.html">List of all members.</a><table border="0" cellpadding="0" cellspacing="0">
<tr><td></td></tr>
<tr><td colspan="2"><br><h2>Public Member Functions</h2></td></tr>
<tr><td class="memItemLeft" nowrap align="right" valign="top">&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="classcupp_1_1exception_1_1cuda__runtime__error.html#3b97c66d5db642e22996e698e6fd866d">cuda_runtime_error</a> (cudaError_t error)</td></tr>

<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Generates an exception with the error number <em>error</em>.  <a href="#3b97c66d5db642e22996e698e6fd866d"></a><br></td></tr>
<tr><td class="memItemLeft" nowrap align="right" valign="top">char const *&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="classcupp_1_1exception_1_1cuda__runtime__error.html#eb152945b34caf0790a7c5e36a732ff3">what</a> () const  throw ()</td></tr>

</table>
<hr><a name="_details"></a><h2>Detailed Description</h2>
This exception is thrown when an low-level CUDA error occurs, eg. an internal call to cudaMalloc fails. 
<p>
<dl class="author" compact><dt><b>Author:</b></dt><dd>Jens Breitbart </dd></dl>
<dl class="version" compact><dt><b>Version:</b></dt><dd>0.1 </dd></dl>
<dl class="date" compact><dt><b>Date:</b></dt><dd>13.06.2007</dd></dl>
The returned error string is a default CUDA error string. 
<p>
<hr><h2>Constructor &amp; Destructor Documentation</h2>
<a class="anchor" name="3b97c66d5db642e22996e698e6fd866d"></a><!-- doxytag: member="cupp::exception::cuda_runtime_error::cuda_runtime_error" ref="3b97c66d5db642e22996e698e6fd866d" args="(cudaError_t error)" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">cupp::exception::cuda_runtime_error::cuda_runtime_error           </td>
          <td>(</td>
          <td class="paramtype">cudaError_t&nbsp;</td>
          <td class="paramname"> <em>error</em>          </td>
          <td>&nbsp;)&nbsp;</td>
          <td width="100%"><code> [inline]</code></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>
Generates an exception with the error number <em>error</em>. 
<p>
<dl compact><dt><b>Parameters:</b></dt><dd>
  <table border="0" cellspacing="2" cellpadding="0">
    <tr><td valign="top"></td><td valign="top"><em>error</em>&nbsp;</td><td>The error number generated by CUDA </td></tr>
  </table>
</dl>

</div>
</div><p>
<hr><h2>Member Function Documentation</h2>
<a class="anchor" name="eb152945b34caf0790a7c5e36a732ff3"></a><!-- doxytag: member="cupp::exception::cuda_runtime_error::what" ref="eb152945b34caf0790a7c5e36a732ff3" args="() const" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">char const* cupp::exception::cuda_runtime_error::what           </td>
          <td>(</td>
          <td class="paramname">          </td>
          <td>&nbsp;)&nbsp;</td>
          <td width="100%"> const  throw ()<code> [inline, virtual]</code></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>
<dl class="return" compact><dt><b>Returns:</b></dt><dd>An error message in human readable form. </dd></dl>

<p>
Implements <a class="el" href="classcupp_1_1exception_1_1exception.html#f6223e64f0340cd031192153c94ff3d6">cupp::exception::exception</a>.
</div>
</div><p>
<hr>The documentation for this class was generated from the following file:<ul>
<li>/home/jensman/projekte/uni/kapaga/svn/cuda++/trunk/include/exception/<a class="el" href="cuda__runtime__error_8h-source.html">cuda_runtime_error.h</a></ul>
<hr size="1"><address style="align: right;"><small>Generated on Wed Jun 20 17:06:10 2007 for cupp by&nbsp;
<a href="http://www.doxygen.org/index.html">
<img src="doxygen.png" alt="doxygen" align="middle" border="0"></a> 1.5.1 </small></address>
</body>
</html>
